app/urls.py
from django.urls import path
from app.views import *
app_name='app'

urlpatterns=[
    path('app_hai/',app_hai,name='app_hai'),

]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'

urlpatterns=[
    path('app2_bye/',app2_bye,name='app2_bye'),

]

specificnavigation/urls.py
from django.contrib import admin
from django.urls import path,include
import app
import app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app2/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def app_hai(request):
    return render(request,'app_hai.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def app2_bye(request):
    return render(request,'app2_bye.html')

templates/app2_bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is App2_Bye html page</h1>
        <h2>Navigating links</h2>
        <h6><a href="{% url 'app:app_hai' %}">Go to app_hai</a></h6>
    </center>
</body>
</html>

templates/app_hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is App_Hai html page</h1>

        <h2>Navigating links</h2>

        <h6><a href="{% url 'app2:app2_bye' %}">Travel to app2_bye</a></h6>
        
    </center>
    
</body>
</html>